# Schema file for the configuration files of the social_sharing module.
social_sharing.settings:
  type: config_object
  label: 'Social sharing settings'
  mapping:
    entities:
      type: sequence
      label: 'Entities'
      sequence:
        type: integer
        label: 'Status'
    share_services:
      type: sequence
      label: 'Share Services'
      sequence:
        type: share_service.[plugin]
        label: 'Share service'

share_service.*:
  type: mapping
  label: 'Social service settings'
  mapping:
    value:
      type: text
      lable: 'Share Url'
    enabled:
      type: boolean
      lable: 'Status'
    weight:
      type: integer
      lable: 'Weight'
